const FOOD_KEYWORDS: [string, string][] = [
  ['chocolate chip cookie', 'chocolate-chip-cookie'],
  ['chocolate chip', 'chocolate-chips'],
  ['ice cream', 'ice-cream-cone'],
  ['hot dog', 'hot-dog'],
  ['corn dog', 'corn-dog'],
  ['french fries', 'french-fries'],
  ['grilled cheese', 'cheese'],
  ['rice bowl', 'rice-bowl'],
  ['roast chicken', 'roast-chicken'],
  ['miso soup', 'miso-soup'],
  ['sushi roll', 'sushi-roll'],
  ['green apple', 'green-apple'],
  ['peanut butter', 'sandwich'],
  ['cream cheese', 'cheese'],
  ['olive oil', 'olive-oil'],
  ['baked potato', 'baked-potato'],
  ['mac and cheese', 'cheese'],
  ['mac & cheese', 'cheese'],
  ['turkey', 'turkey-leg'],
  ['chicken', 'roast-chicken'],
  ['steak', 'steak'],
  ['beef', 'steak'],
  ['bacon', 'bacon'],
  ['sausage', 'sausage'],
  ['salmon', 'fish'],
  ['tuna', 'fish'],
  ['shrimp', 'small-fish'],
  ['fish', 'fish'],
  ['egg', 'egg'],
  ['dumpling', 'dumpling'],
  ['nigiri', 'nigiri'],
  ['meatball', 'steak'],
  ['apple', 'apple'],
  ['banana', 'banana'],
  ['strawberr', 'strawberry'],
  ['blueberr', 'blueberries'],
  ['grape', 'grapes'],
  ['orange', 'orange'],
  ['watermelon', 'watermelon'],
  ['mango', 'mango'],
  ['peach', 'peach'],
  ['pear', 'pear'],
  ['cherr', 'cherries'],
  ['kiwi', 'kiwi'],
  ['pineapple', 'pineapple'],
  ['lemon', 'lemon'],
  ['raspberr', 'raspberry'],
  ['pomegranate', 'pomegranate'],
  ['melon', 'watermelon'],
  ['carrot', 'carrot'],
  ['broccoli', 'arugula'],
  ['spinach', 'spinach'],
  ['lettuce', 'lettuce'],
  ['tomato', 'tomato'],
  ['cucumber', 'pickle'],
  ['pepper', 'pepper'],
  ['corn', 'corn'],
  ['potato', 'potato'],
  ['mushroom', 'mushroom'],
  ['onion', 'onion'],
  ['cabbage', 'cabbage'],
  ['peas', 'peas'],
  ['avocado', 'avocado'],
  ['eggplant', 'eggplant'],
  ['celery', 'arugula'],
  ['radish', 'radish'],
  ['garlic', 'garlic'],
  ['olive', 'olives'],
  ['edamame', 'peas'],
  ['sandwich', 'sandwich'],
  ['bread', 'bread'],
  ['pasta', 'spaghetti'],
  ['spaghetti', 'spaghetti'],
  ['noodle', 'noodles'],
  ['rice', 'rice-bowl'],
  ['tortilla', 'taco'],
  ['wrap', 'taco'],
  ['taco', 'taco'],
  ['burrito', 'taco'],
  ['bagel', 'bagel'],
  ['croissant', 'croissant'],
  ['toast', 'toast'],
  ['waffle', 'waffle'],
  ['pancake', 'pancake'],
  ['pretzel', 'pretzel'],
  ['pizza', 'pizza'],
  ['burger', 'burger'],
  ['cracker', 'pretzel'],
  ['pita', 'bagel'],
  ['cookie', 'cookie'],
  ['chocolate', 'chocolate-bar'],
  ['candy', 'candy'],
  ['cupcake', 'cupcake'],
  ['cake', 'cake-slice'],
  ['donut', 'donut'],
  ['pie', 'pie'],
  ['yogurt', 'yogurt'],
  ['popsicle', 'popcicle'],
  ['lollipop', 'lollipop'],
  ['brownie', 'chocolate-bar'],
  ['granola', 'cookie'],
  ['muffin', 'cupcake'],
  ['cheese', 'cheese'],
  ['milk', 'milk'],
  ['butter', 'butter'],
];

export function getFoodIcon(foodName: string): string | null {
  const lowerFood = foodName.toLowerCase();

  for (const [keyword, iconKey] of FOOD_KEYWORDS) {
    if (lowerFood.includes(keyword)) {
      return iconKey;
    }
  }

  return null;
}
